
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace BusinessLayer
{
	public abstract class _tblProductImage : SqlClientEntity
	{
		public _tblProductImage()
		{
			this.QuerySource = "tblProductImage";
			this.MappingName = "tblProductImage";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblProductImageLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int AppProductImageID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.AppProductImageID, AppProductImageID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblProductImageLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter AppProductImageID
			{
				get
				{
					return new SqlParameter("@AppProductImageID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppThumbImage
			{
				get
				{
					return new SqlParameter("@AppThumbImage", SqlDbType.VarChar, 1000);
				}
			}
			
			public static SqlParameter AppNormalImage
			{
				get
				{
					return new SqlParameter("@AppNormalImage", SqlDbType.VarChar, 1000);
				}
			}
			
			public static SqlParameter AppLargeImage
			{
				get
				{
					return new SqlParameter("@AppLargeImage", SqlDbType.VarChar, 1000);
				}
			}
			
			public static SqlParameter AppSmallImage
			{
				get
				{
					return new SqlParameter("@AppSmallImage", SqlDbType.VarChar, 1000);
				}
			}
			
			public static SqlParameter AppDisplayOrder
			{
				get
				{
					return new SqlParameter("@AppDisplayOrder", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppIsActive
			{
				get
				{
					return new SqlParameter("@AppIsActive", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter AppIsDefault
			{
				get
				{
					return new SqlParameter("@AppIsDefault", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter AppProductColorID
			{
				get
				{
					return new SqlParameter("@AppProductColorID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string AppProductImageID = "appProductImageID";
            public const string AppThumbImage = "appThumbImage";
            public const string AppNormalImage = "appNormalImage";
            public const string AppLargeImage = "appLargeImage";
            public const string AppSmallImage = "appSmallImage";
            public const string AppDisplayOrder = "appDisplayOrder";
            public const string AppIsActive = "appIsActive";
            public const string AppIsDefault = "appIsDefault";
            public const string AppProductColorID = "appProductColorID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppProductImageID] = _tblProductImage.PropertyNames.AppProductImageID;
					ht[AppThumbImage] = _tblProductImage.PropertyNames.AppThumbImage;
					ht[AppNormalImage] = _tblProductImage.PropertyNames.AppNormalImage;
					ht[AppLargeImage] = _tblProductImage.PropertyNames.AppLargeImage;
					ht[AppSmallImage] = _tblProductImage.PropertyNames.AppSmallImage;
					ht[AppDisplayOrder] = _tblProductImage.PropertyNames.AppDisplayOrder;
					ht[AppIsActive] = _tblProductImage.PropertyNames.AppIsActive;
					ht[AppIsDefault] = _tblProductImage.PropertyNames.AppIsDefault;
					ht[AppProductColorID] = _tblProductImage.PropertyNames.AppProductColorID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string AppProductImageID = "AppProductImageID";
            public const string AppThumbImage = "AppThumbImage";
            public const string AppNormalImage = "AppNormalImage";
            public const string AppLargeImage = "AppLargeImage";
            public const string AppSmallImage = "AppSmallImage";
            public const string AppDisplayOrder = "AppDisplayOrder";
            public const string AppIsActive = "AppIsActive";
            public const string AppIsDefault = "AppIsDefault";
            public const string AppProductColorID = "AppProductColorID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppProductImageID] = _tblProductImage.ColumnNames.AppProductImageID;
					ht[AppThumbImage] = _tblProductImage.ColumnNames.AppThumbImage;
					ht[AppNormalImage] = _tblProductImage.ColumnNames.AppNormalImage;
					ht[AppLargeImage] = _tblProductImage.ColumnNames.AppLargeImage;
					ht[AppSmallImage] = _tblProductImage.ColumnNames.AppSmallImage;
					ht[AppDisplayOrder] = _tblProductImage.ColumnNames.AppDisplayOrder;
					ht[AppIsActive] = _tblProductImage.ColumnNames.AppIsActive;
					ht[AppIsDefault] = _tblProductImage.ColumnNames.AppIsDefault;
					ht[AppProductColorID] = _tblProductImage.ColumnNames.AppProductColorID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string AppProductImageID = "s_AppProductImageID";
            public const string AppThumbImage = "s_AppThumbImage";
            public const string AppNormalImage = "s_AppNormalImage";
            public const string AppLargeImage = "s_AppLargeImage";
            public const string AppSmallImage = "s_AppSmallImage";
            public const string AppDisplayOrder = "s_AppDisplayOrder";
            public const string AppIsActive = "s_AppIsActive";
            public const string AppIsDefault = "s_AppIsDefault";
            public const string AppProductColorID = "s_AppProductColorID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int AppProductImageID
	    {
			get
	        {
				return base.Getint(ColumnNames.AppProductImageID);
			}
			set
	        {
				base.Setint(ColumnNames.AppProductImageID, value);
			}
		}

		public virtual string AppThumbImage
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppThumbImage);
			}
			set
	        {
				base.Setstring(ColumnNames.AppThumbImage, value);
			}
		}

		public virtual string AppNormalImage
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppNormalImage);
			}
			set
	        {
				base.Setstring(ColumnNames.AppNormalImage, value);
			}
		}

		public virtual string AppLargeImage
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppLargeImage);
			}
			set
	        {
				base.Setstring(ColumnNames.AppLargeImage, value);
			}
		}

		public virtual string AppSmallImage
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppSmallImage);
			}
			set
	        {
				base.Setstring(ColumnNames.AppSmallImage, value);
			}
		}

		public virtual int AppDisplayOrder
	    {
			get
	        {
				return base.Getint(ColumnNames.AppDisplayOrder);
			}
			set
	        {
				base.Setint(ColumnNames.AppDisplayOrder, value);
			}
		}

		public virtual bool AppIsActive
	    {
			get
	        {
				return base.Getbool(ColumnNames.AppIsActive);
			}
			set
	        {
				base.Setbool(ColumnNames.AppIsActive, value);
			}
		}

		public virtual bool AppIsDefault
	    {
			get
	        {
				return base.Getbool(ColumnNames.AppIsDefault);
			}
			set
	        {
				base.Setbool(ColumnNames.AppIsDefault, value);
			}
		}

		public virtual int AppProductColorID
	    {
			get
	        {
				return base.Getint(ColumnNames.AppProductColorID);
			}
			set
	        {
				base.Setint(ColumnNames.AppProductColorID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_AppProductImageID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppProductImageID) ? string.Empty : base.GetintAsString(ColumnNames.AppProductImageID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppProductImageID);
				else
					this.AppProductImageID = base.SetintAsString(ColumnNames.AppProductImageID, value);
			}
		}

		public virtual string s_AppThumbImage
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppThumbImage) ? string.Empty : base.GetstringAsString(ColumnNames.AppThumbImage);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppThumbImage);
				else
					this.AppThumbImage = base.SetstringAsString(ColumnNames.AppThumbImage, value);
			}
		}

		public virtual string s_AppNormalImage
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppNormalImage) ? string.Empty : base.GetstringAsString(ColumnNames.AppNormalImage);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppNormalImage);
				else
					this.AppNormalImage = base.SetstringAsString(ColumnNames.AppNormalImage, value);
			}
		}

		public virtual string s_AppLargeImage
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppLargeImage) ? string.Empty : base.GetstringAsString(ColumnNames.AppLargeImage);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppLargeImage);
				else
					this.AppLargeImage = base.SetstringAsString(ColumnNames.AppLargeImage, value);
			}
		}

		public virtual string s_AppSmallImage
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppSmallImage) ? string.Empty : base.GetstringAsString(ColumnNames.AppSmallImage);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppSmallImage);
				else
					this.AppSmallImage = base.SetstringAsString(ColumnNames.AppSmallImage, value);
			}
		}

		public virtual string s_AppDisplayOrder
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppDisplayOrder) ? string.Empty : base.GetintAsString(ColumnNames.AppDisplayOrder);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppDisplayOrder);
				else
					this.AppDisplayOrder = base.SetintAsString(ColumnNames.AppDisplayOrder, value);
			}
		}

		public virtual string s_AppIsActive
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppIsActive) ? string.Empty : base.GetboolAsString(ColumnNames.AppIsActive);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppIsActive);
				else
					this.AppIsActive = base.SetboolAsString(ColumnNames.AppIsActive, value);
			}
		}

		public virtual string s_AppIsDefault
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppIsDefault) ? string.Empty : base.GetboolAsString(ColumnNames.AppIsDefault);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppIsDefault);
				else
					this.AppIsDefault = base.SetboolAsString(ColumnNames.AppIsDefault, value);
			}
		}

		public virtual string s_AppProductColorID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppProductColorID) ? string.Empty : base.GetintAsString(ColumnNames.AppProductColorID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppProductColorID);
				else
					this.AppProductColorID = base.SetintAsString(ColumnNames.AppProductColorID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter AppProductImageID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppProductImageID, Parameters.AppProductImageID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppThumbImage
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppThumbImage, Parameters.AppThumbImage);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppNormalImage
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppNormalImage, Parameters.AppNormalImage);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppLargeImage
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppLargeImage, Parameters.AppLargeImage);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppSmallImage
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppSmallImage, Parameters.AppSmallImage);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppDisplayOrder
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppDisplayOrder, Parameters.AppDisplayOrder);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppIsActive
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppIsActive, Parameters.AppIsActive);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppIsDefault
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppIsDefault, Parameters.AppIsDefault);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppProductColorID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppProductColorID, Parameters.AppProductColorID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter AppProductImageID
		    {
				get
		        {
					if(_AppProductImageID_W == null)
	        	    {
						_AppProductImageID_W = TearOff.AppProductImageID;
					}
					return _AppProductImageID_W;
				}
			}

			public WhereParameter AppThumbImage
		    {
				get
		        {
					if(_AppThumbImage_W == null)
	        	    {
						_AppThumbImage_W = TearOff.AppThumbImage;
					}
					return _AppThumbImage_W;
				}
			}

			public WhereParameter AppNormalImage
		    {
				get
		        {
					if(_AppNormalImage_W == null)
	        	    {
						_AppNormalImage_W = TearOff.AppNormalImage;
					}
					return _AppNormalImage_W;
				}
			}

			public WhereParameter AppLargeImage
		    {
				get
		        {
					if(_AppLargeImage_W == null)
	        	    {
						_AppLargeImage_W = TearOff.AppLargeImage;
					}
					return _AppLargeImage_W;
				}
			}

			public WhereParameter AppSmallImage
		    {
				get
		        {
					if(_AppSmallImage_W == null)
	        	    {
						_AppSmallImage_W = TearOff.AppSmallImage;
					}
					return _AppSmallImage_W;
				}
			}

			public WhereParameter AppDisplayOrder
		    {
				get
		        {
					if(_AppDisplayOrder_W == null)
	        	    {
						_AppDisplayOrder_W = TearOff.AppDisplayOrder;
					}
					return _AppDisplayOrder_W;
				}
			}

			public WhereParameter AppIsActive
		    {
				get
		        {
					if(_AppIsActive_W == null)
	        	    {
						_AppIsActive_W = TearOff.AppIsActive;
					}
					return _AppIsActive_W;
				}
			}

			public WhereParameter AppIsDefault
		    {
				get
		        {
					if(_AppIsDefault_W == null)
	        	    {
						_AppIsDefault_W = TearOff.AppIsDefault;
					}
					return _AppIsDefault_W;
				}
			}

			public WhereParameter AppProductColorID
		    {
				get
		        {
					if(_AppProductColorID_W == null)
	        	    {
						_AppProductColorID_W = TearOff.AppProductColorID;
					}
					return _AppProductColorID_W;
				}
			}

			private WhereParameter _AppProductImageID_W = null;
			private WhereParameter _AppThumbImage_W = null;
			private WhereParameter _AppNormalImage_W = null;
			private WhereParameter _AppLargeImage_W = null;
			private WhereParameter _AppSmallImage_W = null;
			private WhereParameter _AppDisplayOrder_W = null;
			private WhereParameter _AppIsActive_W = null;
			private WhereParameter _AppIsDefault_W = null;
			private WhereParameter _AppProductColorID_W = null;

			public void WhereClauseReset()
			{
				_AppProductImageID_W = null;
				_AppThumbImage_W = null;
				_AppNormalImage_W = null;
				_AppLargeImage_W = null;
				_AppSmallImage_W = null;
				_AppDisplayOrder_W = null;
				_AppIsActive_W = null;
				_AppIsDefault_W = null;
				_AppProductColorID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter AppProductImageID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppProductImageID, Parameters.AppProductImageID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppThumbImage
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppThumbImage, Parameters.AppThumbImage);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppNormalImage
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppNormalImage, Parameters.AppNormalImage);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppLargeImage
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppLargeImage, Parameters.AppLargeImage);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppSmallImage
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppSmallImage, Parameters.AppSmallImage);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppDisplayOrder
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppDisplayOrder, Parameters.AppDisplayOrder);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppIsActive
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppIsActive, Parameters.AppIsActive);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppIsDefault
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppIsDefault, Parameters.AppIsDefault);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppProductColorID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppProductColorID, Parameters.AppProductColorID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter AppProductImageID
		    {
				get
		        {
					if(_AppProductImageID_W == null)
	        	    {
						_AppProductImageID_W = TearOff.AppProductImageID;
					}
					return _AppProductImageID_W;
				}
			}

			public AggregateParameter AppThumbImage
		    {
				get
		        {
					if(_AppThumbImage_W == null)
	        	    {
						_AppThumbImage_W = TearOff.AppThumbImage;
					}
					return _AppThumbImage_W;
				}
			}

			public AggregateParameter AppNormalImage
		    {
				get
		        {
					if(_AppNormalImage_W == null)
	        	    {
						_AppNormalImage_W = TearOff.AppNormalImage;
					}
					return _AppNormalImage_W;
				}
			}

			public AggregateParameter AppLargeImage
		    {
				get
		        {
					if(_AppLargeImage_W == null)
	        	    {
						_AppLargeImage_W = TearOff.AppLargeImage;
					}
					return _AppLargeImage_W;
				}
			}

			public AggregateParameter AppSmallImage
		    {
				get
		        {
					if(_AppSmallImage_W == null)
	        	    {
						_AppSmallImage_W = TearOff.AppSmallImage;
					}
					return _AppSmallImage_W;
				}
			}

			public AggregateParameter AppDisplayOrder
		    {
				get
		        {
					if(_AppDisplayOrder_W == null)
	        	    {
						_AppDisplayOrder_W = TearOff.AppDisplayOrder;
					}
					return _AppDisplayOrder_W;
				}
			}

			public AggregateParameter AppIsActive
		    {
				get
		        {
					if(_AppIsActive_W == null)
	        	    {
						_AppIsActive_W = TearOff.AppIsActive;
					}
					return _AppIsActive_W;
				}
			}

			public AggregateParameter AppIsDefault
		    {
				get
		        {
					if(_AppIsDefault_W == null)
	        	    {
						_AppIsDefault_W = TearOff.AppIsDefault;
					}
					return _AppIsDefault_W;
				}
			}

			public AggregateParameter AppProductColorID
		    {
				get
		        {
					if(_AppProductColorID_W == null)
	        	    {
						_AppProductColorID_W = TearOff.AppProductColorID;
					}
					return _AppProductColorID_W;
				}
			}

			private AggregateParameter _AppProductImageID_W = null;
			private AggregateParameter _AppThumbImage_W = null;
			private AggregateParameter _AppNormalImage_W = null;
			private AggregateParameter _AppLargeImage_W = null;
			private AggregateParameter _AppSmallImage_W = null;
			private AggregateParameter _AppDisplayOrder_W = null;
			private AggregateParameter _AppIsActive_W = null;
			private AggregateParameter _AppIsDefault_W = null;
			private AggregateParameter _AppProductColorID_W = null;

			public void AggregateClauseReset()
			{
				_AppProductImageID_W = null;
				_AppThumbImage_W = null;
				_AppNormalImage_W = null;
				_AppLargeImage_W = null;
				_AppSmallImage_W = null;
				_AppDisplayOrder_W = null;
				_AppIsActive_W = null;
				_AppIsDefault_W = null;
				_AppProductColorID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblProductImageInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.AppProductImageID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblProductImageUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblProductImageDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.AppProductImageID);
			p.SourceColumn = ColumnNames.AppProductImageID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.AppProductImageID);
			p.SourceColumn = ColumnNames.AppProductImageID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppThumbImage);
			p.SourceColumn = ColumnNames.AppThumbImage;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppNormalImage);
			p.SourceColumn = ColumnNames.AppNormalImage;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppLargeImage);
			p.SourceColumn = ColumnNames.AppLargeImage;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppSmallImage);
			p.SourceColumn = ColumnNames.AppSmallImage;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppDisplayOrder);
			p.SourceColumn = ColumnNames.AppDisplayOrder;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppIsActive);
			p.SourceColumn = ColumnNames.AppIsActive;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppIsDefault);
			p.SourceColumn = ColumnNames.AppIsDefault;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppProductColorID);
			p.SourceColumn = ColumnNames.AppProductColorID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
