
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace BusinessLayer
{
	public abstract class _tblCurrency : SqlClientEntity
	{
		public _tblCurrency()
		{
			this.QuerySource = "tblCurrency";
			this.MappingName = "tblCurrency";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblCurrencyLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int AppCurrencyID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.AppCurrencyID, AppCurrencyID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblCurrencyLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter AppCurrencyID
			{
				get
				{
					return new SqlParameter("@AppCurrencyID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppCurrency
			{
				get
				{
					return new SqlParameter("@AppCurrency", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter AppCurrencyCode
			{
				get
				{
					return new SqlParameter("@AppCurrencyCode", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter AppRate
			{
				get
				{
					return new SqlParameter("@AppRate", SqlDbType.Decimal, 0);
				}
			}
			
			public static SqlParameter AppSymbol
			{
				get
				{
					return new SqlParameter("@AppSymbol", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter AppIsActive
			{
				get
				{
					return new SqlParameter("@AppIsActive", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter AppIsDefault
			{
				get
				{
					return new SqlParameter("@AppIsDefault", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter AppDisplayOrder
			{
				get
				{
					return new SqlParameter("@AppDisplayOrder", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string AppCurrencyID = "appCurrencyID";
            public const string AppCurrency = "appCurrency";
            public const string AppCurrencyCode = "appCurrencyCode";
            public const string AppRate = "appRate";
            public const string AppSymbol = "appSymbol";
            public const string AppIsActive = "appIsActive";
            public const string AppIsDefault = "appIsDefault";
            public const string AppDisplayOrder = "appDisplayOrder";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppCurrencyID] = _tblCurrency.PropertyNames.AppCurrencyID;
					ht[AppCurrency] = _tblCurrency.PropertyNames.AppCurrency;
					ht[AppCurrencyCode] = _tblCurrency.PropertyNames.AppCurrencyCode;
					ht[AppRate] = _tblCurrency.PropertyNames.AppRate;
					ht[AppSymbol] = _tblCurrency.PropertyNames.AppSymbol;
					ht[AppIsActive] = _tblCurrency.PropertyNames.AppIsActive;
					ht[AppIsDefault] = _tblCurrency.PropertyNames.AppIsDefault;
					ht[AppDisplayOrder] = _tblCurrency.PropertyNames.AppDisplayOrder;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string AppCurrencyID = "AppCurrencyID";
            public const string AppCurrency = "AppCurrency";
            public const string AppCurrencyCode = "AppCurrencyCode";
            public const string AppRate = "AppRate";
            public const string AppSymbol = "AppSymbol";
            public const string AppIsActive = "AppIsActive";
            public const string AppIsDefault = "AppIsDefault";
            public const string AppDisplayOrder = "AppDisplayOrder";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppCurrencyID] = _tblCurrency.ColumnNames.AppCurrencyID;
					ht[AppCurrency] = _tblCurrency.ColumnNames.AppCurrency;
					ht[AppCurrencyCode] = _tblCurrency.ColumnNames.AppCurrencyCode;
					ht[AppRate] = _tblCurrency.ColumnNames.AppRate;
					ht[AppSymbol] = _tblCurrency.ColumnNames.AppSymbol;
					ht[AppIsActive] = _tblCurrency.ColumnNames.AppIsActive;
					ht[AppIsDefault] = _tblCurrency.ColumnNames.AppIsDefault;
					ht[AppDisplayOrder] = _tblCurrency.ColumnNames.AppDisplayOrder;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string AppCurrencyID = "s_AppCurrencyID";
            public const string AppCurrency = "s_AppCurrency";
            public const string AppCurrencyCode = "s_AppCurrencyCode";
            public const string AppRate = "s_AppRate";
            public const string AppSymbol = "s_AppSymbol";
            public const string AppIsActive = "s_AppIsActive";
            public const string AppIsDefault = "s_AppIsDefault";
            public const string AppDisplayOrder = "s_AppDisplayOrder";

		}
		#endregion		
		
		#region Properties
	
		public virtual int AppCurrencyID
	    {
			get
	        {
				return base.Getint(ColumnNames.AppCurrencyID);
			}
			set
	        {
				base.Setint(ColumnNames.AppCurrencyID, value);
			}
		}

		public virtual string AppCurrency
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppCurrency);
			}
			set
	        {
				base.Setstring(ColumnNames.AppCurrency, value);
			}
		}

		public virtual string AppCurrencyCode
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppCurrencyCode);
			}
			set
	        {
				base.Setstring(ColumnNames.AppCurrencyCode, value);
			}
		}

		public virtual decimal AppRate
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.AppRate);
			}
			set
	        {
				base.Setdecimal(ColumnNames.AppRate, value);
			}
		}

		public virtual string AppSymbol
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppSymbol);
			}
			set
	        {
				base.Setstring(ColumnNames.AppSymbol, value);
			}
		}

		public virtual bool AppIsActive
	    {
			get
	        {
				return base.Getbool(ColumnNames.AppIsActive);
			}
			set
	        {
				base.Setbool(ColumnNames.AppIsActive, value);
			}
		}

		public virtual bool AppIsDefault
	    {
			get
	        {
				return base.Getbool(ColumnNames.AppIsDefault);
			}
			set
	        {
				base.Setbool(ColumnNames.AppIsDefault, value);
			}
		}

		public virtual int AppDisplayOrder
	    {
			get
	        {
				return base.Getint(ColumnNames.AppDisplayOrder);
			}
			set
	        {
				base.Setint(ColumnNames.AppDisplayOrder, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_AppCurrencyID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppCurrencyID) ? string.Empty : base.GetintAsString(ColumnNames.AppCurrencyID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppCurrencyID);
				else
					this.AppCurrencyID = base.SetintAsString(ColumnNames.AppCurrencyID, value);
			}
		}

		public virtual string s_AppCurrency
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppCurrency) ? string.Empty : base.GetstringAsString(ColumnNames.AppCurrency);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppCurrency);
				else
					this.AppCurrency = base.SetstringAsString(ColumnNames.AppCurrency, value);
			}
		}

		public virtual string s_AppCurrencyCode
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppCurrencyCode) ? string.Empty : base.GetstringAsString(ColumnNames.AppCurrencyCode);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppCurrencyCode);
				else
					this.AppCurrencyCode = base.SetstringAsString(ColumnNames.AppCurrencyCode, value);
			}
		}

		public virtual string s_AppRate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppRate) ? string.Empty : base.GetdecimalAsString(ColumnNames.AppRate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppRate);
				else
					this.AppRate = base.SetdecimalAsString(ColumnNames.AppRate, value);
			}
		}

		public virtual string s_AppSymbol
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppSymbol) ? string.Empty : base.GetstringAsString(ColumnNames.AppSymbol);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppSymbol);
				else
					this.AppSymbol = base.SetstringAsString(ColumnNames.AppSymbol, value);
			}
		}

		public virtual string s_AppIsActive
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppIsActive) ? string.Empty : base.GetboolAsString(ColumnNames.AppIsActive);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppIsActive);
				else
					this.AppIsActive = base.SetboolAsString(ColumnNames.AppIsActive, value);
			}
		}

		public virtual string s_AppIsDefault
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppIsDefault) ? string.Empty : base.GetboolAsString(ColumnNames.AppIsDefault);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppIsDefault);
				else
					this.AppIsDefault = base.SetboolAsString(ColumnNames.AppIsDefault, value);
			}
		}

		public virtual string s_AppDisplayOrder
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppDisplayOrder) ? string.Empty : base.GetintAsString(ColumnNames.AppDisplayOrder);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppDisplayOrder);
				else
					this.AppDisplayOrder = base.SetintAsString(ColumnNames.AppDisplayOrder, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter AppCurrencyID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppCurrencyID, Parameters.AppCurrencyID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppCurrency
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppCurrency, Parameters.AppCurrency);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppCurrencyCode
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppCurrencyCode, Parameters.AppCurrencyCode);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppRate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppRate, Parameters.AppRate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppSymbol
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppSymbol, Parameters.AppSymbol);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppIsActive
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppIsActive, Parameters.AppIsActive);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppIsDefault
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppIsDefault, Parameters.AppIsDefault);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppDisplayOrder
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppDisplayOrder, Parameters.AppDisplayOrder);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter AppCurrencyID
		    {
				get
		        {
					if(_AppCurrencyID_W == null)
	        	    {
						_AppCurrencyID_W = TearOff.AppCurrencyID;
					}
					return _AppCurrencyID_W;
				}
			}

			public WhereParameter AppCurrency
		    {
				get
		        {
					if(_AppCurrency_W == null)
	        	    {
						_AppCurrency_W = TearOff.AppCurrency;
					}
					return _AppCurrency_W;
				}
			}

			public WhereParameter AppCurrencyCode
		    {
				get
		        {
					if(_AppCurrencyCode_W == null)
	        	    {
						_AppCurrencyCode_W = TearOff.AppCurrencyCode;
					}
					return _AppCurrencyCode_W;
				}
			}

			public WhereParameter AppRate
		    {
				get
		        {
					if(_AppRate_W == null)
	        	    {
						_AppRate_W = TearOff.AppRate;
					}
					return _AppRate_W;
				}
			}

			public WhereParameter AppSymbol
		    {
				get
		        {
					if(_AppSymbol_W == null)
	        	    {
						_AppSymbol_W = TearOff.AppSymbol;
					}
					return _AppSymbol_W;
				}
			}

			public WhereParameter AppIsActive
		    {
				get
		        {
					if(_AppIsActive_W == null)
	        	    {
						_AppIsActive_W = TearOff.AppIsActive;
					}
					return _AppIsActive_W;
				}
			}

			public WhereParameter AppIsDefault
		    {
				get
		        {
					if(_AppIsDefault_W == null)
	        	    {
						_AppIsDefault_W = TearOff.AppIsDefault;
					}
					return _AppIsDefault_W;
				}
			}

			public WhereParameter AppDisplayOrder
		    {
				get
		        {
					if(_AppDisplayOrder_W == null)
	        	    {
						_AppDisplayOrder_W = TearOff.AppDisplayOrder;
					}
					return _AppDisplayOrder_W;
				}
			}

			private WhereParameter _AppCurrencyID_W = null;
			private WhereParameter _AppCurrency_W = null;
			private WhereParameter _AppCurrencyCode_W = null;
			private WhereParameter _AppRate_W = null;
			private WhereParameter _AppSymbol_W = null;
			private WhereParameter _AppIsActive_W = null;
			private WhereParameter _AppIsDefault_W = null;
			private WhereParameter _AppDisplayOrder_W = null;

			public void WhereClauseReset()
			{
				_AppCurrencyID_W = null;
				_AppCurrency_W = null;
				_AppCurrencyCode_W = null;
				_AppRate_W = null;
				_AppSymbol_W = null;
				_AppIsActive_W = null;
				_AppIsDefault_W = null;
				_AppDisplayOrder_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter AppCurrencyID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppCurrencyID, Parameters.AppCurrencyID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppCurrency
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppCurrency, Parameters.AppCurrency);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppCurrencyCode
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppCurrencyCode, Parameters.AppCurrencyCode);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppRate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppRate, Parameters.AppRate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppSymbol
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppSymbol, Parameters.AppSymbol);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppIsActive
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppIsActive, Parameters.AppIsActive);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppIsDefault
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppIsDefault, Parameters.AppIsDefault);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppDisplayOrder
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppDisplayOrder, Parameters.AppDisplayOrder);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter AppCurrencyID
		    {
				get
		        {
					if(_AppCurrencyID_W == null)
	        	    {
						_AppCurrencyID_W = TearOff.AppCurrencyID;
					}
					return _AppCurrencyID_W;
				}
			}

			public AggregateParameter AppCurrency
		    {
				get
		        {
					if(_AppCurrency_W == null)
	        	    {
						_AppCurrency_W = TearOff.AppCurrency;
					}
					return _AppCurrency_W;
				}
			}

			public AggregateParameter AppCurrencyCode
		    {
				get
		        {
					if(_AppCurrencyCode_W == null)
	        	    {
						_AppCurrencyCode_W = TearOff.AppCurrencyCode;
					}
					return _AppCurrencyCode_W;
				}
			}

			public AggregateParameter AppRate
		    {
				get
		        {
					if(_AppRate_W == null)
	        	    {
						_AppRate_W = TearOff.AppRate;
					}
					return _AppRate_W;
				}
			}

			public AggregateParameter AppSymbol
		    {
				get
		        {
					if(_AppSymbol_W == null)
	        	    {
						_AppSymbol_W = TearOff.AppSymbol;
					}
					return _AppSymbol_W;
				}
			}

			public AggregateParameter AppIsActive
		    {
				get
		        {
					if(_AppIsActive_W == null)
	        	    {
						_AppIsActive_W = TearOff.AppIsActive;
					}
					return _AppIsActive_W;
				}
			}

			public AggregateParameter AppIsDefault
		    {
				get
		        {
					if(_AppIsDefault_W == null)
	        	    {
						_AppIsDefault_W = TearOff.AppIsDefault;
					}
					return _AppIsDefault_W;
				}
			}

			public AggregateParameter AppDisplayOrder
		    {
				get
		        {
					if(_AppDisplayOrder_W == null)
	        	    {
						_AppDisplayOrder_W = TearOff.AppDisplayOrder;
					}
					return _AppDisplayOrder_W;
				}
			}

			private AggregateParameter _AppCurrencyID_W = null;
			private AggregateParameter _AppCurrency_W = null;
			private AggregateParameter _AppCurrencyCode_W = null;
			private AggregateParameter _AppRate_W = null;
			private AggregateParameter _AppSymbol_W = null;
			private AggregateParameter _AppIsActive_W = null;
			private AggregateParameter _AppIsDefault_W = null;
			private AggregateParameter _AppDisplayOrder_W = null;

			public void AggregateClauseReset()
			{
				_AppCurrencyID_W = null;
				_AppCurrency_W = null;
				_AppCurrencyCode_W = null;
				_AppRate_W = null;
				_AppSymbol_W = null;
				_AppIsActive_W = null;
				_AppIsDefault_W = null;
				_AppDisplayOrder_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblCurrencyInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.AppCurrencyID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblCurrencyUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblCurrencyDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.AppCurrencyID);
			p.SourceColumn = ColumnNames.AppCurrencyID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.AppCurrencyID);
			p.SourceColumn = ColumnNames.AppCurrencyID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppCurrency);
			p.SourceColumn = ColumnNames.AppCurrency;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppCurrencyCode);
			p.SourceColumn = ColumnNames.AppCurrencyCode;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppRate);
			p.SourceColumn = ColumnNames.AppRate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppSymbol);
			p.SourceColumn = ColumnNames.AppSymbol;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppIsActive);
			p.SourceColumn = ColumnNames.AppIsActive;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppIsDefault);
			p.SourceColumn = ColumnNames.AppIsDefault;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppDisplayOrder);
			p.SourceColumn = ColumnNames.AppDisplayOrder;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
