
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace BusinessLayer
{
	public abstract class _tblManifest : SqlClientEntity
	{
		public _tblManifest()
		{
			this.QuerySource = "tblManifest";
			this.MappingName = "tblManifest";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblManifestLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int AppManifestID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.AppManifestID, AppManifestID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblManifestLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter AppManifestID
			{
				get
				{
					return new SqlParameter("@AppManifestID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppUploadedManifest
			{
				get
				{
					return new SqlParameter("@AppUploadedManifest", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter AppCreatedDate
			{
				get
				{
					return new SqlParameter("@AppCreatedDate", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string AppManifestID = "appManifestID";
            public const string AppUploadedManifest = "appUploadedManifest";
            public const string AppCreatedDate = "appCreatedDate";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppManifestID] = _tblManifest.PropertyNames.AppManifestID;
					ht[AppUploadedManifest] = _tblManifest.PropertyNames.AppUploadedManifest;
					ht[AppCreatedDate] = _tblManifest.PropertyNames.AppCreatedDate;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string AppManifestID = "AppManifestID";
            public const string AppUploadedManifest = "AppUploadedManifest";
            public const string AppCreatedDate = "AppCreatedDate";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppManifestID] = _tblManifest.ColumnNames.AppManifestID;
					ht[AppUploadedManifest] = _tblManifest.ColumnNames.AppUploadedManifest;
					ht[AppCreatedDate] = _tblManifest.ColumnNames.AppCreatedDate;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string AppManifestID = "s_AppManifestID";
            public const string AppUploadedManifest = "s_AppUploadedManifest";
            public const string AppCreatedDate = "s_AppCreatedDate";

		}
		#endregion		
		
		#region Properties
	
		public virtual int AppManifestID
	    {
			get
	        {
				return base.Getint(ColumnNames.AppManifestID);
			}
			set
	        {
				base.Setint(ColumnNames.AppManifestID, value);
			}
		}

		public virtual string AppUploadedManifest
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppUploadedManifest);
			}
			set
	        {
				base.Setstring(ColumnNames.AppUploadedManifest, value);
			}
		}

		public virtual DateTime AppCreatedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.AppCreatedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.AppCreatedDate, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_AppManifestID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppManifestID) ? string.Empty : base.GetintAsString(ColumnNames.AppManifestID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppManifestID);
				else
					this.AppManifestID = base.SetintAsString(ColumnNames.AppManifestID, value);
			}
		}

		public virtual string s_AppUploadedManifest
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppUploadedManifest) ? string.Empty : base.GetstringAsString(ColumnNames.AppUploadedManifest);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppUploadedManifest);
				else
					this.AppUploadedManifest = base.SetstringAsString(ColumnNames.AppUploadedManifest, value);
			}
		}

		public virtual string s_AppCreatedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppCreatedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.AppCreatedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppCreatedDate);
				else
					this.AppCreatedDate = base.SetDateTimeAsString(ColumnNames.AppCreatedDate, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter AppManifestID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppManifestID, Parameters.AppManifestID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppUploadedManifest
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppUploadedManifest, Parameters.AppUploadedManifest);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppCreatedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppCreatedDate, Parameters.AppCreatedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter AppManifestID
		    {
				get
		        {
					if(_AppManifestID_W == null)
	        	    {
						_AppManifestID_W = TearOff.AppManifestID;
					}
					return _AppManifestID_W;
				}
			}

			public WhereParameter AppUploadedManifest
		    {
				get
		        {
					if(_AppUploadedManifest_W == null)
	        	    {
						_AppUploadedManifest_W = TearOff.AppUploadedManifest;
					}
					return _AppUploadedManifest_W;
				}
			}

			public WhereParameter AppCreatedDate
		    {
				get
		        {
					if(_AppCreatedDate_W == null)
	        	    {
						_AppCreatedDate_W = TearOff.AppCreatedDate;
					}
					return _AppCreatedDate_W;
				}
			}

			private WhereParameter _AppManifestID_W = null;
			private WhereParameter _AppUploadedManifest_W = null;
			private WhereParameter _AppCreatedDate_W = null;

			public void WhereClauseReset()
			{
				_AppManifestID_W = null;
				_AppUploadedManifest_W = null;
				_AppCreatedDate_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter AppManifestID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppManifestID, Parameters.AppManifestID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppUploadedManifest
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppUploadedManifest, Parameters.AppUploadedManifest);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppCreatedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppCreatedDate, Parameters.AppCreatedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter AppManifestID
		    {
				get
		        {
					if(_AppManifestID_W == null)
	        	    {
						_AppManifestID_W = TearOff.AppManifestID;
					}
					return _AppManifestID_W;
				}
			}

			public AggregateParameter AppUploadedManifest
		    {
				get
		        {
					if(_AppUploadedManifest_W == null)
	        	    {
						_AppUploadedManifest_W = TearOff.AppUploadedManifest;
					}
					return _AppUploadedManifest_W;
				}
			}

			public AggregateParameter AppCreatedDate
		    {
				get
		        {
					if(_AppCreatedDate_W == null)
	        	    {
						_AppCreatedDate_W = TearOff.AppCreatedDate;
					}
					return _AppCreatedDate_W;
				}
			}

			private AggregateParameter _AppManifestID_W = null;
			private AggregateParameter _AppUploadedManifest_W = null;
			private AggregateParameter _AppCreatedDate_W = null;

			public void AggregateClauseReset()
			{
				_AppManifestID_W = null;
				_AppUploadedManifest_W = null;
				_AppCreatedDate_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblManifestInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.AppManifestID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblManifestUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblManifestDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.AppManifestID);
			p.SourceColumn = ColumnNames.AppManifestID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.AppManifestID);
			p.SourceColumn = ColumnNames.AppManifestID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppUploadedManifest);
			p.SourceColumn = ColumnNames.AppUploadedManifest;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppCreatedDate);
			p.SourceColumn = ColumnNames.AppCreatedDate;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
