
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace BusinessLayer
{
	public abstract class _tblSentSMS : SqlClientEntity
	{
		public _tblSentSMS()
		{
			this.QuerySource = "tblSentSMS";
			this.MappingName = "tblSentSMS";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblSentSMSLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int AppSentSMSID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.AppSentSMSID, AppSentSMSID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblSentSMSLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter AppSentSMSID
			{
				get
				{
					return new SqlParameter("@AppSentSMSID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppSentDate
			{
				get
				{
					return new SqlParameter("@AppSentDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter AppText
			{
				get
				{
					return new SqlParameter("@AppText", SqlDbType.VarChar, 500);
				}
			}
			
			public static SqlParameter AppMobileNo
			{
				get
				{
					return new SqlParameter("@AppMobileNo", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter AppSentBy
			{
				get
				{
					return new SqlParameter("@AppSentBy", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string AppSentSMSID = "appSentSMSID";
            public const string AppSentDate = "appSentDate";
            public const string AppText = "appText";
            public const string AppMobileNo = "appMobileNo";
            public const string AppSentBy = "appSentBy";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppSentSMSID] = _tblSentSMS.PropertyNames.AppSentSMSID;
					ht[AppSentDate] = _tblSentSMS.PropertyNames.AppSentDate;
					ht[AppText] = _tblSentSMS.PropertyNames.AppText;
					ht[AppMobileNo] = _tblSentSMS.PropertyNames.AppMobileNo;
					ht[AppSentBy] = _tblSentSMS.PropertyNames.AppSentBy;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string AppSentSMSID = "AppSentSMSID";
            public const string AppSentDate = "AppSentDate";
            public const string AppText = "AppText";
            public const string AppMobileNo = "AppMobileNo";
            public const string AppSentBy = "AppSentBy";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppSentSMSID] = _tblSentSMS.ColumnNames.AppSentSMSID;
					ht[AppSentDate] = _tblSentSMS.ColumnNames.AppSentDate;
					ht[AppText] = _tblSentSMS.ColumnNames.AppText;
					ht[AppMobileNo] = _tblSentSMS.ColumnNames.AppMobileNo;
					ht[AppSentBy] = _tblSentSMS.ColumnNames.AppSentBy;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string AppSentSMSID = "s_AppSentSMSID";
            public const string AppSentDate = "s_AppSentDate";
            public const string AppText = "s_AppText";
            public const string AppMobileNo = "s_AppMobileNo";
            public const string AppSentBy = "s_AppSentBy";

		}
		#endregion		
		
		#region Properties
	
		public virtual int AppSentSMSID
	    {
			get
	        {
				return base.Getint(ColumnNames.AppSentSMSID);
			}
			set
	        {
				base.Setint(ColumnNames.AppSentSMSID, value);
			}
		}

		public virtual DateTime AppSentDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.AppSentDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.AppSentDate, value);
			}
		}

		public virtual string AppText
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppText);
			}
			set
	        {
				base.Setstring(ColumnNames.AppText, value);
			}
		}

		public virtual string AppMobileNo
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppMobileNo);
			}
			set
	        {
				base.Setstring(ColumnNames.AppMobileNo, value);
			}
		}

		public virtual int AppSentBy
	    {
			get
	        {
				return base.Getint(ColumnNames.AppSentBy);
			}
			set
	        {
				base.Setint(ColumnNames.AppSentBy, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_AppSentSMSID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppSentSMSID) ? string.Empty : base.GetintAsString(ColumnNames.AppSentSMSID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppSentSMSID);
				else
					this.AppSentSMSID = base.SetintAsString(ColumnNames.AppSentSMSID, value);
			}
		}

		public virtual string s_AppSentDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppSentDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.AppSentDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppSentDate);
				else
					this.AppSentDate = base.SetDateTimeAsString(ColumnNames.AppSentDate, value);
			}
		}

		public virtual string s_AppText
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppText) ? string.Empty : base.GetstringAsString(ColumnNames.AppText);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppText);
				else
					this.AppText = base.SetstringAsString(ColumnNames.AppText, value);
			}
		}

		public virtual string s_AppMobileNo
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppMobileNo) ? string.Empty : base.GetstringAsString(ColumnNames.AppMobileNo);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppMobileNo);
				else
					this.AppMobileNo = base.SetstringAsString(ColumnNames.AppMobileNo, value);
			}
		}

		public virtual string s_AppSentBy
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppSentBy) ? string.Empty : base.GetintAsString(ColumnNames.AppSentBy);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppSentBy);
				else
					this.AppSentBy = base.SetintAsString(ColumnNames.AppSentBy, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter AppSentSMSID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppSentSMSID, Parameters.AppSentSMSID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppSentDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppSentDate, Parameters.AppSentDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppText
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppText, Parameters.AppText);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppMobileNo
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppMobileNo, Parameters.AppMobileNo);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppSentBy
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppSentBy, Parameters.AppSentBy);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter AppSentSMSID
		    {
				get
		        {
					if(_AppSentSMSID_W == null)
	        	    {
						_AppSentSMSID_W = TearOff.AppSentSMSID;
					}
					return _AppSentSMSID_W;
				}
			}

			public WhereParameter AppSentDate
		    {
				get
		        {
					if(_AppSentDate_W == null)
	        	    {
						_AppSentDate_W = TearOff.AppSentDate;
					}
					return _AppSentDate_W;
				}
			}

			public WhereParameter AppText
		    {
				get
		        {
					if(_AppText_W == null)
	        	    {
						_AppText_W = TearOff.AppText;
					}
					return _AppText_W;
				}
			}

			public WhereParameter AppMobileNo
		    {
				get
		        {
					if(_AppMobileNo_W == null)
	        	    {
						_AppMobileNo_W = TearOff.AppMobileNo;
					}
					return _AppMobileNo_W;
				}
			}

			public WhereParameter AppSentBy
		    {
				get
		        {
					if(_AppSentBy_W == null)
	        	    {
						_AppSentBy_W = TearOff.AppSentBy;
					}
					return _AppSentBy_W;
				}
			}

			private WhereParameter _AppSentSMSID_W = null;
			private WhereParameter _AppSentDate_W = null;
			private WhereParameter _AppText_W = null;
			private WhereParameter _AppMobileNo_W = null;
			private WhereParameter _AppSentBy_W = null;

			public void WhereClauseReset()
			{
				_AppSentSMSID_W = null;
				_AppSentDate_W = null;
				_AppText_W = null;
				_AppMobileNo_W = null;
				_AppSentBy_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter AppSentSMSID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppSentSMSID, Parameters.AppSentSMSID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppSentDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppSentDate, Parameters.AppSentDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppText
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppText, Parameters.AppText);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppMobileNo
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppMobileNo, Parameters.AppMobileNo);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppSentBy
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppSentBy, Parameters.AppSentBy);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter AppSentSMSID
		    {
				get
		        {
					if(_AppSentSMSID_W == null)
	        	    {
						_AppSentSMSID_W = TearOff.AppSentSMSID;
					}
					return _AppSentSMSID_W;
				}
			}

			public AggregateParameter AppSentDate
		    {
				get
		        {
					if(_AppSentDate_W == null)
	        	    {
						_AppSentDate_W = TearOff.AppSentDate;
					}
					return _AppSentDate_W;
				}
			}

			public AggregateParameter AppText
		    {
				get
		        {
					if(_AppText_W == null)
	        	    {
						_AppText_W = TearOff.AppText;
					}
					return _AppText_W;
				}
			}

			public AggregateParameter AppMobileNo
		    {
				get
		        {
					if(_AppMobileNo_W == null)
	        	    {
						_AppMobileNo_W = TearOff.AppMobileNo;
					}
					return _AppMobileNo_W;
				}
			}

			public AggregateParameter AppSentBy
		    {
				get
		        {
					if(_AppSentBy_W == null)
	        	    {
						_AppSentBy_W = TearOff.AppSentBy;
					}
					return _AppSentBy_W;
				}
			}

			private AggregateParameter _AppSentSMSID_W = null;
			private AggregateParameter _AppSentDate_W = null;
			private AggregateParameter _AppText_W = null;
			private AggregateParameter _AppMobileNo_W = null;
			private AggregateParameter _AppSentBy_W = null;

			public void AggregateClauseReset()
			{
				_AppSentSMSID_W = null;
				_AppSentDate_W = null;
				_AppText_W = null;
				_AppMobileNo_W = null;
				_AppSentBy_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblSentSMSInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.AppSentSMSID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblSentSMSUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblSentSMSDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.AppSentSMSID);
			p.SourceColumn = ColumnNames.AppSentSMSID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.AppSentSMSID);
			p.SourceColumn = ColumnNames.AppSentSMSID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppSentDate);
			p.SourceColumn = ColumnNames.AppSentDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppText);
			p.SourceColumn = ColumnNames.AppText;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppMobileNo);
			p.SourceColumn = ColumnNames.AppMobileNo;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppSentBy);
			p.SourceColumn = ColumnNames.AppSentBy;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
