
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace BusinessLayer
{
	public abstract class _tblProductSubCategory : SqlClientEntity
	{
		public _tblProductSubCategory()
		{
			this.QuerySource = "tblProductSubCategory";
			this.MappingName = "tblProductSubCategory";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblProductSubCategoryLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int AppProductSubCategoryID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.AppProductSubCategoryID, AppProductSubCategoryID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblProductSubCategoryLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter AppProductSubCategoryID
			{
				get
				{
					return new SqlParameter("@AppProductSubCategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppSubCategoryID
			{
				get
				{
					return new SqlParameter("@AppSubCategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppProductID
			{
				get
				{
					return new SqlParameter("@AppProductID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppDisplayOrder
			{
				get
				{
					return new SqlParameter("@AppDisplayOrder", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppIsActive
			{
				get
				{
					return new SqlParameter("@AppIsActive", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string AppProductSubCategoryID = "appProductSubCategoryID";
            public const string AppSubCategoryID = "appSubCategoryID";
            public const string AppProductID = "appProductID";
            public const string AppDisplayOrder = "appDisplayOrder";
            public const string AppIsActive = "appIsActive";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppProductSubCategoryID] = _tblProductSubCategory.PropertyNames.AppProductSubCategoryID;
					ht[AppSubCategoryID] = _tblProductSubCategory.PropertyNames.AppSubCategoryID;
					ht[AppProductID] = _tblProductSubCategory.PropertyNames.AppProductID;
					ht[AppDisplayOrder] = _tblProductSubCategory.PropertyNames.AppDisplayOrder;
					ht[AppIsActive] = _tblProductSubCategory.PropertyNames.AppIsActive;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string AppProductSubCategoryID = "AppProductSubCategoryID";
            public const string AppSubCategoryID = "AppSubCategoryID";
            public const string AppProductID = "AppProductID";
            public const string AppDisplayOrder = "AppDisplayOrder";
            public const string AppIsActive = "AppIsActive";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppProductSubCategoryID] = _tblProductSubCategory.ColumnNames.AppProductSubCategoryID;
					ht[AppSubCategoryID] = _tblProductSubCategory.ColumnNames.AppSubCategoryID;
					ht[AppProductID] = _tblProductSubCategory.ColumnNames.AppProductID;
					ht[AppDisplayOrder] = _tblProductSubCategory.ColumnNames.AppDisplayOrder;
					ht[AppIsActive] = _tblProductSubCategory.ColumnNames.AppIsActive;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string AppProductSubCategoryID = "s_AppProductSubCategoryID";
            public const string AppSubCategoryID = "s_AppSubCategoryID";
            public const string AppProductID = "s_AppProductID";
            public const string AppDisplayOrder = "s_AppDisplayOrder";
            public const string AppIsActive = "s_AppIsActive";

		}
		#endregion		
		
		#region Properties
	
		public virtual int AppProductSubCategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.AppProductSubCategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.AppProductSubCategoryID, value);
			}
		}

		public virtual int AppSubCategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.AppSubCategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.AppSubCategoryID, value);
			}
		}

		public virtual int AppProductID
	    {
			get
	        {
				return base.Getint(ColumnNames.AppProductID);
			}
			set
	        {
				base.Setint(ColumnNames.AppProductID, value);
			}
		}

		public virtual int AppDisplayOrder
	    {
			get
	        {
				return base.Getint(ColumnNames.AppDisplayOrder);
			}
			set
	        {
				base.Setint(ColumnNames.AppDisplayOrder, value);
			}
		}

		public virtual bool AppIsActive
	    {
			get
	        {
				return base.Getbool(ColumnNames.AppIsActive);
			}
			set
	        {
				base.Setbool(ColumnNames.AppIsActive, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_AppProductSubCategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppProductSubCategoryID) ? string.Empty : base.GetintAsString(ColumnNames.AppProductSubCategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppProductSubCategoryID);
				else
					this.AppProductSubCategoryID = base.SetintAsString(ColumnNames.AppProductSubCategoryID, value);
			}
		}

		public virtual string s_AppSubCategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppSubCategoryID) ? string.Empty : base.GetintAsString(ColumnNames.AppSubCategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppSubCategoryID);
				else
					this.AppSubCategoryID = base.SetintAsString(ColumnNames.AppSubCategoryID, value);
			}
		}

		public virtual string s_AppProductID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppProductID) ? string.Empty : base.GetintAsString(ColumnNames.AppProductID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppProductID);
				else
					this.AppProductID = base.SetintAsString(ColumnNames.AppProductID, value);
			}
		}

		public virtual string s_AppDisplayOrder
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppDisplayOrder) ? string.Empty : base.GetintAsString(ColumnNames.AppDisplayOrder);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppDisplayOrder);
				else
					this.AppDisplayOrder = base.SetintAsString(ColumnNames.AppDisplayOrder, value);
			}
		}

		public virtual string s_AppIsActive
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppIsActive) ? string.Empty : base.GetboolAsString(ColumnNames.AppIsActive);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppIsActive);
				else
					this.AppIsActive = base.SetboolAsString(ColumnNames.AppIsActive, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter AppProductSubCategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppProductSubCategoryID, Parameters.AppProductSubCategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppSubCategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppSubCategoryID, Parameters.AppSubCategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppProductID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppProductID, Parameters.AppProductID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppDisplayOrder
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppDisplayOrder, Parameters.AppDisplayOrder);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppIsActive
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppIsActive, Parameters.AppIsActive);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter AppProductSubCategoryID
		    {
				get
		        {
					if(_AppProductSubCategoryID_W == null)
	        	    {
						_AppProductSubCategoryID_W = TearOff.AppProductSubCategoryID;
					}
					return _AppProductSubCategoryID_W;
				}
			}

			public WhereParameter AppSubCategoryID
		    {
				get
		        {
					if(_AppSubCategoryID_W == null)
	        	    {
						_AppSubCategoryID_W = TearOff.AppSubCategoryID;
					}
					return _AppSubCategoryID_W;
				}
			}

			public WhereParameter AppProductID
		    {
				get
		        {
					if(_AppProductID_W == null)
	        	    {
						_AppProductID_W = TearOff.AppProductID;
					}
					return _AppProductID_W;
				}
			}

			public WhereParameter AppDisplayOrder
		    {
				get
		        {
					if(_AppDisplayOrder_W == null)
	        	    {
						_AppDisplayOrder_W = TearOff.AppDisplayOrder;
					}
					return _AppDisplayOrder_W;
				}
			}

			public WhereParameter AppIsActive
		    {
				get
		        {
					if(_AppIsActive_W == null)
	        	    {
						_AppIsActive_W = TearOff.AppIsActive;
					}
					return _AppIsActive_W;
				}
			}

			private WhereParameter _AppProductSubCategoryID_W = null;
			private WhereParameter _AppSubCategoryID_W = null;
			private WhereParameter _AppProductID_W = null;
			private WhereParameter _AppDisplayOrder_W = null;
			private WhereParameter _AppIsActive_W = null;

			public void WhereClauseReset()
			{
				_AppProductSubCategoryID_W = null;
				_AppSubCategoryID_W = null;
				_AppProductID_W = null;
				_AppDisplayOrder_W = null;
				_AppIsActive_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter AppProductSubCategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppProductSubCategoryID, Parameters.AppProductSubCategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppSubCategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppSubCategoryID, Parameters.AppSubCategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppProductID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppProductID, Parameters.AppProductID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppDisplayOrder
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppDisplayOrder, Parameters.AppDisplayOrder);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppIsActive
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppIsActive, Parameters.AppIsActive);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter AppProductSubCategoryID
		    {
				get
		        {
					if(_AppProductSubCategoryID_W == null)
	        	    {
						_AppProductSubCategoryID_W = TearOff.AppProductSubCategoryID;
					}
					return _AppProductSubCategoryID_W;
				}
			}

			public AggregateParameter AppSubCategoryID
		    {
				get
		        {
					if(_AppSubCategoryID_W == null)
	        	    {
						_AppSubCategoryID_W = TearOff.AppSubCategoryID;
					}
					return _AppSubCategoryID_W;
				}
			}

			public AggregateParameter AppProductID
		    {
				get
		        {
					if(_AppProductID_W == null)
	        	    {
						_AppProductID_W = TearOff.AppProductID;
					}
					return _AppProductID_W;
				}
			}

			public AggregateParameter AppDisplayOrder
		    {
				get
		        {
					if(_AppDisplayOrder_W == null)
	        	    {
						_AppDisplayOrder_W = TearOff.AppDisplayOrder;
					}
					return _AppDisplayOrder_W;
				}
			}

			public AggregateParameter AppIsActive
		    {
				get
		        {
					if(_AppIsActive_W == null)
	        	    {
						_AppIsActive_W = TearOff.AppIsActive;
					}
					return _AppIsActive_W;
				}
			}

			private AggregateParameter _AppProductSubCategoryID_W = null;
			private AggregateParameter _AppSubCategoryID_W = null;
			private AggregateParameter _AppProductID_W = null;
			private AggregateParameter _AppDisplayOrder_W = null;
			private AggregateParameter _AppIsActive_W = null;

			public void AggregateClauseReset()
			{
				_AppProductSubCategoryID_W = null;
				_AppSubCategoryID_W = null;
				_AppProductID_W = null;
				_AppDisplayOrder_W = null;
				_AppIsActive_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblProductSubCategoryInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.AppProductSubCategoryID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblProductSubCategoryUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblProductSubCategoryDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.AppProductSubCategoryID);
			p.SourceColumn = ColumnNames.AppProductSubCategoryID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.AppProductSubCategoryID);
			p.SourceColumn = ColumnNames.AppProductSubCategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppSubCategoryID);
			p.SourceColumn = ColumnNames.AppSubCategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppProductID);
			p.SourceColumn = ColumnNames.AppProductID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppDisplayOrder);
			p.SourceColumn = ColumnNames.AppDisplayOrder;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppIsActive);
			p.SourceColumn = ColumnNames.AppIsActive;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
