
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace BusinessLayer
{
	public abstract class _tblMenuItemType : SqlClientEntity
	{
		public _tblMenuItemType()
		{
			this.QuerySource = "tblMenuItemType";
			this.MappingName = "tblMenuItemType";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblMenuItemTypeLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int AppMenuItemTypeID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.AppMenuItemTypeID, AppMenuItemTypeID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_tblMenuItemTypeLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter AppMenuItemTypeID
			{
				get
				{
					return new SqlParameter("@AppMenuItemTypeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppMenuItemType
			{
				get
				{
					return new SqlParameter("@AppMenuItemType", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter AppIsActive
			{
				get
				{
					return new SqlParameter("@AppIsActive", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter AppDisplayOrder
			{
				get
				{
					return new SqlParameter("@AppDisplayOrder", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AppCreateDate
			{
				get
				{
					return new SqlParameter("@AppCreateDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter AppCreateBy
			{
				get
				{
					return new SqlParameter("@AppCreateBy", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string AppMenuItemTypeID = "appMenuItemTypeID";
            public const string AppMenuItemType = "appMenuItemType";
            public const string AppIsActive = "appIsActive";
            public const string AppDisplayOrder = "appDisplayOrder";
            public const string AppCreateDate = "appCreateDate";
            public const string AppCreateBy = "appCreateBy";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppMenuItemTypeID] = _tblMenuItemType.PropertyNames.AppMenuItemTypeID;
					ht[AppMenuItemType] = _tblMenuItemType.PropertyNames.AppMenuItemType;
					ht[AppIsActive] = _tblMenuItemType.PropertyNames.AppIsActive;
					ht[AppDisplayOrder] = _tblMenuItemType.PropertyNames.AppDisplayOrder;
					ht[AppCreateDate] = _tblMenuItemType.PropertyNames.AppCreateDate;
					ht[AppCreateBy] = _tblMenuItemType.PropertyNames.AppCreateBy;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string AppMenuItemTypeID = "AppMenuItemTypeID";
            public const string AppMenuItemType = "AppMenuItemType";
            public const string AppIsActive = "AppIsActive";
            public const string AppDisplayOrder = "AppDisplayOrder";
            public const string AppCreateDate = "AppCreateDate";
            public const string AppCreateBy = "AppCreateBy";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[AppMenuItemTypeID] = _tblMenuItemType.ColumnNames.AppMenuItemTypeID;
					ht[AppMenuItemType] = _tblMenuItemType.ColumnNames.AppMenuItemType;
					ht[AppIsActive] = _tblMenuItemType.ColumnNames.AppIsActive;
					ht[AppDisplayOrder] = _tblMenuItemType.ColumnNames.AppDisplayOrder;
					ht[AppCreateDate] = _tblMenuItemType.ColumnNames.AppCreateDate;
					ht[AppCreateBy] = _tblMenuItemType.ColumnNames.AppCreateBy;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string AppMenuItemTypeID = "s_AppMenuItemTypeID";
            public const string AppMenuItemType = "s_AppMenuItemType";
            public const string AppIsActive = "s_AppIsActive";
            public const string AppDisplayOrder = "s_AppDisplayOrder";
            public const string AppCreateDate = "s_AppCreateDate";
            public const string AppCreateBy = "s_AppCreateBy";

		}
		#endregion		
		
		#region Properties
	
		public virtual int AppMenuItemTypeID
	    {
			get
	        {
				return base.Getint(ColumnNames.AppMenuItemTypeID);
			}
			set
	        {
				base.Setint(ColumnNames.AppMenuItemTypeID, value);
			}
		}

		public virtual string AppMenuItemType
	    {
			get
	        {
				return base.Getstring(ColumnNames.AppMenuItemType);
			}
			set
	        {
				base.Setstring(ColumnNames.AppMenuItemType, value);
			}
		}

		public virtual bool AppIsActive
	    {
			get
	        {
				return base.Getbool(ColumnNames.AppIsActive);
			}
			set
	        {
				base.Setbool(ColumnNames.AppIsActive, value);
			}
		}

		public virtual int AppDisplayOrder
	    {
			get
	        {
				return base.Getint(ColumnNames.AppDisplayOrder);
			}
			set
	        {
				base.Setint(ColumnNames.AppDisplayOrder, value);
			}
		}

		public virtual DateTime AppCreateDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.AppCreateDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.AppCreateDate, value);
			}
		}

		public virtual int AppCreateBy
	    {
			get
	        {
				return base.Getint(ColumnNames.AppCreateBy);
			}
			set
	        {
				base.Setint(ColumnNames.AppCreateBy, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_AppMenuItemTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppMenuItemTypeID) ? string.Empty : base.GetintAsString(ColumnNames.AppMenuItemTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppMenuItemTypeID);
				else
					this.AppMenuItemTypeID = base.SetintAsString(ColumnNames.AppMenuItemTypeID, value);
			}
		}

		public virtual string s_AppMenuItemType
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppMenuItemType) ? string.Empty : base.GetstringAsString(ColumnNames.AppMenuItemType);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppMenuItemType);
				else
					this.AppMenuItemType = base.SetstringAsString(ColumnNames.AppMenuItemType, value);
			}
		}

		public virtual string s_AppIsActive
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppIsActive) ? string.Empty : base.GetboolAsString(ColumnNames.AppIsActive);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppIsActive);
				else
					this.AppIsActive = base.SetboolAsString(ColumnNames.AppIsActive, value);
			}
		}

		public virtual string s_AppDisplayOrder
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppDisplayOrder) ? string.Empty : base.GetintAsString(ColumnNames.AppDisplayOrder);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppDisplayOrder);
				else
					this.AppDisplayOrder = base.SetintAsString(ColumnNames.AppDisplayOrder, value);
			}
		}

		public virtual string s_AppCreateDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppCreateDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.AppCreateDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppCreateDate);
				else
					this.AppCreateDate = base.SetDateTimeAsString(ColumnNames.AppCreateDate, value);
			}
		}

		public virtual string s_AppCreateBy
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AppCreateBy) ? string.Empty : base.GetintAsString(ColumnNames.AppCreateBy);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AppCreateBy);
				else
					this.AppCreateBy = base.SetintAsString(ColumnNames.AppCreateBy, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter AppMenuItemTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppMenuItemTypeID, Parameters.AppMenuItemTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppMenuItemType
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppMenuItemType, Parameters.AppMenuItemType);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppIsActive
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppIsActive, Parameters.AppIsActive);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppDisplayOrder
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppDisplayOrder, Parameters.AppDisplayOrder);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppCreateDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppCreateDate, Parameters.AppCreateDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AppCreateBy
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AppCreateBy, Parameters.AppCreateBy);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter AppMenuItemTypeID
		    {
				get
		        {
					if(_AppMenuItemTypeID_W == null)
	        	    {
						_AppMenuItemTypeID_W = TearOff.AppMenuItemTypeID;
					}
					return _AppMenuItemTypeID_W;
				}
			}

			public WhereParameter AppMenuItemType
		    {
				get
		        {
					if(_AppMenuItemType_W == null)
	        	    {
						_AppMenuItemType_W = TearOff.AppMenuItemType;
					}
					return _AppMenuItemType_W;
				}
			}

			public WhereParameter AppIsActive
		    {
				get
		        {
					if(_AppIsActive_W == null)
	        	    {
						_AppIsActive_W = TearOff.AppIsActive;
					}
					return _AppIsActive_W;
				}
			}

			public WhereParameter AppDisplayOrder
		    {
				get
		        {
					if(_AppDisplayOrder_W == null)
	        	    {
						_AppDisplayOrder_W = TearOff.AppDisplayOrder;
					}
					return _AppDisplayOrder_W;
				}
			}

			public WhereParameter AppCreateDate
		    {
				get
		        {
					if(_AppCreateDate_W == null)
	        	    {
						_AppCreateDate_W = TearOff.AppCreateDate;
					}
					return _AppCreateDate_W;
				}
			}

			public WhereParameter AppCreateBy
		    {
				get
		        {
					if(_AppCreateBy_W == null)
	        	    {
						_AppCreateBy_W = TearOff.AppCreateBy;
					}
					return _AppCreateBy_W;
				}
			}

			private WhereParameter _AppMenuItemTypeID_W = null;
			private WhereParameter _AppMenuItemType_W = null;
			private WhereParameter _AppIsActive_W = null;
			private WhereParameter _AppDisplayOrder_W = null;
			private WhereParameter _AppCreateDate_W = null;
			private WhereParameter _AppCreateBy_W = null;

			public void WhereClauseReset()
			{
				_AppMenuItemTypeID_W = null;
				_AppMenuItemType_W = null;
				_AppIsActive_W = null;
				_AppDisplayOrder_W = null;
				_AppCreateDate_W = null;
				_AppCreateBy_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter AppMenuItemTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppMenuItemTypeID, Parameters.AppMenuItemTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppMenuItemType
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppMenuItemType, Parameters.AppMenuItemType);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppIsActive
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppIsActive, Parameters.AppIsActive);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppDisplayOrder
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppDisplayOrder, Parameters.AppDisplayOrder);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppCreateDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppCreateDate, Parameters.AppCreateDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AppCreateBy
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AppCreateBy, Parameters.AppCreateBy);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter AppMenuItemTypeID
		    {
				get
		        {
					if(_AppMenuItemTypeID_W == null)
	        	    {
						_AppMenuItemTypeID_W = TearOff.AppMenuItemTypeID;
					}
					return _AppMenuItemTypeID_W;
				}
			}

			public AggregateParameter AppMenuItemType
		    {
				get
		        {
					if(_AppMenuItemType_W == null)
	        	    {
						_AppMenuItemType_W = TearOff.AppMenuItemType;
					}
					return _AppMenuItemType_W;
				}
			}

			public AggregateParameter AppIsActive
		    {
				get
		        {
					if(_AppIsActive_W == null)
	        	    {
						_AppIsActive_W = TearOff.AppIsActive;
					}
					return _AppIsActive_W;
				}
			}

			public AggregateParameter AppDisplayOrder
		    {
				get
		        {
					if(_AppDisplayOrder_W == null)
	        	    {
						_AppDisplayOrder_W = TearOff.AppDisplayOrder;
					}
					return _AppDisplayOrder_W;
				}
			}

			public AggregateParameter AppCreateDate
		    {
				get
		        {
					if(_AppCreateDate_W == null)
	        	    {
						_AppCreateDate_W = TearOff.AppCreateDate;
					}
					return _AppCreateDate_W;
				}
			}

			public AggregateParameter AppCreateBy
		    {
				get
		        {
					if(_AppCreateBy_W == null)
	        	    {
						_AppCreateBy_W = TearOff.AppCreateBy;
					}
					return _AppCreateBy_W;
				}
			}

			private AggregateParameter _AppMenuItemTypeID_W = null;
			private AggregateParameter _AppMenuItemType_W = null;
			private AggregateParameter _AppIsActive_W = null;
			private AggregateParameter _AppDisplayOrder_W = null;
			private AggregateParameter _AppCreateDate_W = null;
			private AggregateParameter _AppCreateBy_W = null;

			public void AggregateClauseReset()
			{
				_AppMenuItemTypeID_W = null;
				_AppMenuItemType_W = null;
				_AppIsActive_W = null;
				_AppDisplayOrder_W = null;
				_AppCreateDate_W = null;
				_AppCreateBy_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblMenuItemTypeInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.AppMenuItemTypeID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblMenuItemTypeUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_tblMenuItemTypeDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.AppMenuItemTypeID);
			p.SourceColumn = ColumnNames.AppMenuItemTypeID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.AppMenuItemTypeID);
			p.SourceColumn = ColumnNames.AppMenuItemTypeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppMenuItemType);
			p.SourceColumn = ColumnNames.AppMenuItemType;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppIsActive);
			p.SourceColumn = ColumnNames.AppIsActive;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppDisplayOrder);
			p.SourceColumn = ColumnNames.AppDisplayOrder;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppCreateDate);
			p.SourceColumn = ColumnNames.AppCreateDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AppCreateBy);
			p.SourceColumn = ColumnNames.AppCreateBy;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
